# Generated by Django 4.1.6 on 2023-02-03 20:49

from django.db import migrations, models
import generate.validators


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0002_profile_save_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditsBuyPriceAndCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_count', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[generate.validators.validate_positive])),
            ],
        ),
    ]
