# Generated by Django 4.1.6 on 2023-02-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0003_contentstyles_delete_letterstyles_delete_poemstyles'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='have_answers',
            field=models.BooleanField(default=True),
        ),
    ]
