# Generated by Django 4.1.6 on 2023-02-03 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import generate.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generate', '0003_creditsbuypriceandcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_count', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[generate.validators.validate_positive])),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
