# Generated by Django 4.1.6 on 2023-02-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0004_questions_have_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptsHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.TextField()),
            ],
        ),
    ]
