# Generated by Django 4.1.6 on 2023-02-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0005_scriptshead'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='questions',
            name='my_order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
