# Generated by Django 4.1.6 on 2023-02-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0007_alter_profile_save_answers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'ordering': ['my_order']},
        ),
        migrations.AlterModelOptions(
            name='length',
            options={'ordering': ['my_order']},
        ),
        migrations.AlterModelOptions(
            name='letterstyles',
            options={'ordering': ['my_order']},
        ),
        migrations.AlterModelOptions(
            name='occasion',
            options={'ordering': ['my_order']},
        ),
        migrations.AlterModelOptions(
            name='poemstyles',
            options={'ordering': ['my_order']},
        ),
        migrations.AlterModelOptions(
            name='relationshiptypes',
            options={'ordering': ['my_order']},
        ),
        migrations.AlterModelOptions(
            name='tone',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='answers',
            name='my_order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='length',
            name='my_order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='letterstyles',
            name='my_order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='occasion',
            name='my_order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='poemstyles',
            name='my_order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='relationshiptypes',
            name='my_order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='tone',
            name='my_order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
