# Generated by Django 4.1.6 on 2023-02-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0008_alter_answers_options_alter_length_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='save_answers',
            field=models.JSONField(null=True),
        ),
    ]
